### ISSUE TITLE
Editor breaks on login with new account

### ISSUE THREAD

**Issue by nick-verida** [verida/markdown-notes-demo#100]
When logging in the first time with a brand new account I get this

![image](https://user-images.githubusercontent.com/87622993/148002192-34a46abd-2f25-45ee-9463-1732efbf5e76.png)

**Comment by nick-verida** [comment]
Removing cookies/storage to log out, and logging in again seems to fix the issue

**Comment by nick-verida** [comment]
Related report from @kalanamt 
![image](https://user-images.githubusercontent.com/87622993/148002450-ba7b1fe0-db8e-4592-8d5c-2a318a7763fd.png)

**Comment by nick-verida** [comment]
Note that my stacktrace from from an incognito mode Firefox browser

**Comment by cmcWebCode40** [comment]
@nick-verida, I'm still unable to reproduce this exact error.

- I created a new account
- logged in using a  incognito mode chrome

I will have to install firefox to continue testing

**Comment by nick-verida** [comment]
@cmcWebCode40 don't worry about the exact error - I think just reproducing that there is a problem with brand new accounts would be sufficient.

**Comment by nick-verida** [comment]
@cmcWebCode40 this error seems to be back
