### ISSUE TITLE
Make Markdown Editor work on Mobile

### ISSUE THREAD

**Issue by nick-verida** [verida/markdown-notes-demo#118]
Should function the same as on mobile. 

At least the following issues exist
* No way to add new note
* Menu button mostly off screen
* Display of notes wrong (compare to desktop display)

<img src="https://user-images.githubusercontent.com/87622993/167351029-bb16decc-0511-47d3-a3a1-13be3dfc772f.png" width="300px">

When editing a note buttons are misaligned

<img src="https://user-images.githubusercontent.com/87622993/167351284-79e1407e-53cc-429a-87ae-cc34cab39c90.png" width="300px">

https://markdown-editor.demos.testnet.verida.io/

**Comment by ysam21** [comment]
![image](https://user-images.githubusercontent.com/92969583/167355820-9e4799de-9ba7-4ac6-b3a8-f63e0df32abc.png)

- Pressing menu button doesn't do anything
- Marking and unmarking as favourite doesn't change the star colour
