### ISSUE TITLE
[Bug]: Profile details not saving on signup and Error in connecting with vault

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/markdown-notes-demo#60]
1. I got this error trying to connect with the client library using the new account I created from the verida vault-app see a screenshot of the error here 
<img width="1328" alt="Screenshot 2021-09-09 at 17 09 48" src="https://user-images.githubusercontent.com/54280620/132788416-d7b93731-1296-4c26-a968-48cc7abed459.png">

2. I just login in now with a  new account and I noticed that the initial profile details (name, country) I entered while creating my account in the vault were not set so I noticed this while connecting with the `client library` I had to update my profile details again before it was saved.

**Comment by tahpot** [comment]
Closing, no longer an issue.
