### ISSUE TITLE
404 page when app is refreshed

### ISSUE THREAD

**Issue by cmcWebCode40** [verida/markdown-notes-demo#80]
When I refresh the markdown app, from the `/connect` or `/editor` page it displays this error

<img width="1303" alt="Screenshot 2021-09-19 at 08 20 00" src="https://user-images.githubusercontent.com/54280620/133919131-cd8d0e04-63fd-4b5a-bb82-c072177c1c8b.png">

could it be from AWS redirect configurations?

**Comment by tahpot** [comment]
I've noticed this too.

@nick-verida Take a look at some of the other cloudfront distributions I created and their redirect settings. I have been configuring 404's to redirect to `/index`, this then allows the React / Vue routers to pickup the appropriate URL and load as expected. It's an incredibly annoying hack.

**Comment by nick-verida** [comment]
We didn't have any redirects in place for the markdown editor bucket (or for cloudfront).

After some research I've done this: https://stackoverflow.com/a/60704255/280795 (ie. set the error page to index.html). This is pretty easy to do, but still pretty horrible. 

@tahpot @cmcWebCode40 can you verify it is working how it should be? I'm not sure of all the URLs it should be covering.

**Comment by tahpot** [comment]
@nick-verida Yes, this appears to be working as expected.

Visiting `https://markdown-editor.demos.testnet.verida.io/connect` now loads the QR code instead of a 404.

**Comment by cmcWebCode40** [comment]
@nick-verida, i just tested now, its working as expected

**Comment by nick-verida** [comment]
ok, closing this.
