### ISSUE TITLE
Saving notes doesn't work

### ISSUE THREAD

**Issue by nick-verida** [verida/markdown-notes-demo#98]
Steps:
* Go to https://markdown-editor.demos.testnet.verida.io/
* Log in
* Create new note
* Save note
<img width="350" alt="image" src="https://user-images.githubusercontent.com/87622993/142286181-b25e07e4-fe27-476f-ad2c-c4a76d1b01d5.png">

It's possible this is related to this in the console:

```
Blocked loading mixed active content “http://json-schema.org/draft-07/schema”
```

**Comment by tahpot** [comment]
@cmcWebCode40 I suspect the markdown editor schemas need updating, much like the MAPay schemas?

**Comment by cmcWebCode40** [comment]
@tahpot , i think so too, i'm currently updating the schema

**Comment by nick-verida** [comment]
Note that we need to fix the `http` vs `https` error even if there are mandatory fields in the schema that have changed too. 

Schemas should be referenced over https.
